wireplumber.settings = {
  node.restore-default-targets = false
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source hsp_hs hfp_hf hfp_ag ]
  bluez5.hfphsp-backend = "native"
}

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ hfp_hf hsp_hs a2dp_sink ]
      }
    }
  }
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1400
      }
    }
  }
  {
    matches = [
      {
        node.name = "~bluez_input.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2200
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.pci-0000_00_1f.3.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 900
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_input.pci-0000_00_1f.3.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1800
      }
    }
  }
]
