[bar/main]
monitor = ${env:MONITOR}

width = 88%
offset-x = 6%
offset-y = 10
height = 28
radius = 6
fixed-center = true

override-redirect = true
wm-restack = i3

background = #282c34
foreground = #abb2bf

border-size = 1
border-color = #3e4451

font-0 = "JetBrainsMono Nerd Font:size=12;3"
font-1 = "JetBrainsMono Nerd Font:size=13;3"
; font-1 = "Noto Color Eoji:scale=11:3"
font-2 = "Noto Sans Symbols:size=14;3"

modules-left = i3
modules-center = date weather
modules-right = reboot recording cpu disk memory battery volume mic tray

enable-ipc = true
strip-wsnumbers = true

[bar/main-secondary]
monitor = ${env:MONITOR}

width = 88%
offset-x = 6%
offset-y = 10
height = 28
radius = 6
fixed-center = true

override-redirect = true
wm-restack = i3

background = #282c34
foreground = #abb2bf

border-size = 1
border-color = #3e4451

font-0 = "JetBrainsMono Nerd Font:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=11;3"
; font-1 = "Noto Color Emoji:scale=11:3"
font-2 = "Noto Sans Symbols:size=14;3"

modules-left = i3
modules-center = date weather
modules-right = reboot recording cpu disk memory volume mic

enable-ipc = true
strip-wsnumbers = true

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
pin-workspaces = true
format-padding = 2

label-focused = %{T2}%name%%{T-}
label-focused-foreground = #61afef
label-focused-background = #282c34
label-focused-padding = 2

label-visible = %{T2}%name%%{T-}
label-visible-foreground = #5c6370
label-visible-background = #282c34
label-visible-padding = 2

label-unfocused = %{T2}%name%%{T-}
label-unfocused-foreground = #5c6370
label-unfocused-background = #282c34
label-unfocused-padding = 2

label-urgent = %{T2}%name%%{T-}
label-urgent-foreground = #e06c75
label-urgent-background = #282c34
label-urgent-padding = 2

strip-wsnumbers = true


[module/date]
type = internal/date
interval = 1
date = %a %d %b
time = %H:%M
label-font = 2
label = %{A1:sh -c 'GTK_THEME=Pinentry-OneDark /usr/bin/gsimplecal &':}%date% %time%%{A}

[module/cpu]
type = internal/cpu
interval = 2
label =  %{T2}%{T-}  %percentage%%
format-padding = 3

[module/disk]
type = internal/fs
mount-0 = /
label-mounted = %{T2}%{T-}  %percentage_used%%
format-padding = 3

[module/memory]
type = internal/memory
interval = 2
label = %{T2}󰘚%{T-}  %percentage_used%%
format-padding = 3

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
poll-interval = 1
format-discharging = <label-discharging>
label-discharging =  %percentage%%
format-charging =
format-full =
format-padding = 3

[module/volume]
type = custom/script
exec = ~/.config/polybar/volume.sh
interval = 1
format = <label>
format-padding = 3

[module/mic]
type = custom/script
exec = wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED && echo "" || echo ""
interval = 1
format-padding = 2

click-left = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
scroll-up = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
scroll-down = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

[module/tray]
type = internal/tray
format-padding = 2

[module/weather]
type = custom/script
exec = ~/.local/bin/weather
interval = 60
label-font = 2
format-padding = 3
click-left = ~/.local/bin/weather-select

[module/recording]
type = custom/script
exec = ~/.local/bin/ffrecord-status
tail = true
format = <label>
format-padding = 1

[module/reboot]
type = custom/script
exec = ~/.local/bin/checkreboot
interval = 5

format-foreground = #ff0000
format-padding = 1
click-left = ~/.local/bin/ffrecord


